# A python script to count the words of a given text string.


text = """In the first chapter, the models of this dissertation is presented and a dimensionless variational form is derived. The model problems used in the dissertation is also presented.

In the second chapter, we look at the existence and uniqueness of solutions for a general vibration problem. All of the models in this dissertation is a special case of this general vibration problem. So a cantilever Timoshenko beam model is used as an example of the application of the theory as well as to explain the theory. A weak variational form of a cantilever Timoshenko beam model is derived. The authors provide four assumptions, and using these assumptions they prove using semi-group theory that the general vibration problem has a unique solution. For the example, we show that the four assumptions can be proven for the cantilever Timoshenko beam model.

Then we look at modal analysis. Again we use the cantilever Timoshenko beam model as an example. A trial solution is chosen and using this trial solution, two problems are obtained. The first is the eigenvalue problem and the second is an ordinary differential equation. These two problems are solved and substitution then shows that the trial solution is valid. This is similar to the separation of variables, but it avoids any division. We then discuss a general solution using the same idea. The idea of modal analysis is crucial to the dissertation. From modal analysis, we can compare the eigenvalues and eigenfunctions of the models, and if they compare well, then the solutions of the models will compare well. And since the formal series solution is a linear combination of Fourier Coefficients, we only need to consider the first few eigenvalues.

In the third chapter, two theoretical results are considered for the Finite Element Method. The first results is on the convergence of the Galerkin Approximation of a general vibration problem. In this section, the results of the article is discussed. The results are also given in Theorems with simple notation. We then look at a result form a textbook on the convergence of the eigenvalues and eigenfunctions when using the Finite Element Method. We discuss the results of the textbook, with some improvements to the notation as well as expanding some results to make it more clear.

In the fourth chapter, we look at our simplest model, the Timoshenko beam model. The first result discusses an article that provides a method to determine the exact eigenvalues and eigenfunctions for the Timoshenko beam model. We then apply this to a cantilever beam model and a free-free beam model to obtain the eigenvalues and plot the mode shapes. We then look at an article that compares a cantilever Timoshenko beam model to a two-dimensional beam model. We discuss the results of the article and replicate the results with more significant digits. We also include some more results not included in the article, that are used later in Chapter 6. We then look at another article that compares the Timoshenko beam theory to results obtained from a measured beam. The authors suspended a beam on both ends an vibrated the beam until then endpoints could be considered free. They then swept through different frequencies and recorded the natural frequencies of the beam. These results are then compared to the theoretical results of a free-free Timoshenko beam. We add to the article by giving the model problems for the beams and discuss the results.

The fifth chapter is a preparation chapter for the comparisons of this dissertation. In chapter 4, we have a method to obtain the exact eigenvalues and eigenfunctions for the Timoshenko beam theory. But a different approach is required for the two- and three-dimensional models. In this chapter, we derive the Galerkin Approximation for each of the models. We then define a discrete grid of elements on the reference configuration on each of the models. Then using piece-wise Hermite cubic basis functions, we derive a matrix representation of the model problems using the standard Finite Element Analysis. In this form it is then easy to obtain a matrix representation of the eigenvalue problem for each of the models. This is in preparation for the comparisons of the models in Section 4.5 as well as chapter 6.

In the final chapter, we extend the work of Section 4.5 and investigate the validity of the two-dimensional beam model as well as the validity of the Reissner-Mindlin plate model. Using the work from chapter 5, a numerical formula is derived to calculate the eigenvalues and eigenvectors of the models. This is implemented into some MATLAB code. (This was also done to obtain the results in Section 4.5). The same structure as Section 4.5 is followed. To start, the mode shapes are calculated and plotted. These are then compared so that the eigenvalues can be matched up. Careful consideration should be taken to the shapes as there are many shapes not relating to beam-type or plate-type problems. The results show that the shape of the models impact how well the models compare. The cases of the comparisons were chosen so that they represent realistic scenarios for use in application.
"""

word_count = len(text.split())

print("The text contains {} words".format(word_count))